### ISSUE TITLE
WorldGuard compatibility?

### ISSUE THREAD

**Issue by capuano1** [TheTechdoodle/rideable-enderpearl#1]
Hello, I would like to know if you could add something like if WorldGuard is installed on the server, to check if the place the player is throwing the enderpearl has the enderpearl region flag. If it has and it's denied, make so the player don't ride the enderpearl. I need this because I made a parkour on my lobby inside a closed structure, so no one can use the enderpearl outside the region and throw it somewhere on the parkour, but if someone throw a enderpearl inside that structure (that has the enderpearl deny flag), since she ride it, she actually end up getting to the place she threw the enderpearl at. I know that's a lot to ask (since it involves another plugin), so if it's not possible, it's okay.

**Comment by techchrism** [comment]
I'll look into how easy/difficult this is. As a temporary workaround, you could look into granting/denying the "rideableenderpearl.ride" permission based on the region. I found this plugin but I haven't tested it so it may not work: https://dev.bukkit.org/projects/regionperms

**Comment by techchrism** [comment]
WorldGuard integration has been added in 1.3.0
